#import ...
import numpy as np

#defind
a = np.array([1, 2, 3])
b = np.array([1, 2, 3], dtype = np.int64)
c = np.array([[1, 2, 3],
                    [2, 3, 4]])
d = np.zeros((3, 4))
e = np.zeros((3, 4), dtype = np.int16)
f = np.ones((3, 4))
g = np.ones((3, 4), dtype = np.int32)
h = np.empty((3, 4))
i = np.arange(10, 20)
j = np.arange(12).reshape((3, 4))
k = np.linspace(1, 10, 6).reshape((2, 3))

#caculate
l = np.array([10, 20, 30, 40])
m = np.arange(4)
n = l + m
o = l - m
p = l * m
q = l**m
r = l * np.sin(m)
s = l * np.cos(m)
t = l * np.tan(m)
t_dot = np.dot(l, m)
t_dot_sample = l.dot(m)
u  =np.random.random((2, 4))
v = np.sum(l)
w = np.min(l)
x = np.max(l)
y = np.sum(m)
z = np.min(m)
A = np.max(m)
B = np.sum(l, axis = 0)
C = np.min(l, axis = 0)
D = np.max(l, axis = 0)
E = np.arange(2, 14).reshape((3, 4))
F = np.argmin(E)
G = np.argmax(E)
H = np.mean(E)
I = np.average(E)
J = np.median(E)
K = np.cumsum(E)
L = np.diff(E)
M = np.nonzero(E)
N = np.sort(E)

#TRY
O = np.arange(3, 15).reshape((3, 4))
for row in O:
        print(row)
  
for col in O.T:
        print(cul)

#print
print(a)
print(b)
print(b.dtype)
print(c)
print(d)
print(e)
print(f)
print(g)
print(h)
print(i)
print(j)
print(k)
print(l)
print(m)
print(n)
print(o)
print(p)
print(q)
print(r)
print(s)
print(t)
print(t_dot)
print(t_dot_sample)
print(u)
print(v)
print(w)
print(x)
print(y)
print(z)
print(A)
print(B)
print(C)
print(D)
print(E)
print(F)
print(G)
print(H)
print(I)
print(J)
print(K)
print(L)
print(M)
print(N)
